sudo: false
services:
  - docker
#dist: trusty
language: node_js
node_js:
  - 4.6.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
env:
  DOCKER_COMPOSE_VERSION: 1.9.0
  global:
    - secure: IVNUEIDEb4Uh/5T+SXIrPuQV8x33Kzhf9oE4hIdsSQFKDNqophryVpSo3Xg34SX1ZViVau9TU8ec2E3zTxPSDyeW5Emfo7Xhzf/6oUQaN3OW+xi1HSCUGg7Tq5jIdRDnVXgFnWLl2fRoGtOrz5lfvQ5e3q6+EpCPyVDUpEjlVNDTibWvibKj4d5BR349THpOeGOUbzr87uke1TOxBkbsceVt55G3xyYRNI6DfLg4MjqaYLzhf5WnduwZc5RyZLFC5EHEhvxRy0BOfbpF20NBva05qjO1GcuNaHPfJhuuQcsaSAGmzHXi67QvDAjmCLLd7lA5HwCC2+51CGccw/CqnM64cZIJVMZnh68wd9gRHszKU8VhMx8K2eNPcGa5WTER+ald5pK2XBycm/fUNPTy/3zf30Svk5l9pyuT22WepGHmWrPxU3HzxpyGE0zPcPmzVjl23J40PBIHAHt3p2yoX2fQOKsA7c7dci6lcgX/aO3g6UGY8nd8OtEmeP9FybgVgNqJGdQP6gtT7rk6zf0lStbkC0RWu52GvLxTLthDgaQkqOFjwc0tVDYydsNZ/n046uDXw1eytt8lJT7ayu0+mnT2jzsLBvCDia1uwVRr5zHZUAuYHk+P5FM7yMjv5BaMwMbnSxU1AgIe+n0ojeb/f5wuKMBbGXTReyszPrXq/AY=

before_install:
  - export CC="gcc-4.9" CXX="g++-4.9"
before_script:
  - npm install -g bower
  - npm install
  - bower install --allow-root --no-interactive
  - apt-get install -y openssh-server
  - echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKoYF0n2YwxcUxutgd76bnqx/CXmi8EvsHg28yoMmwQYwHCTkgCbf2vGQK29EcoSKjVw480mA/iHIDn2ymLQFisbCraX7VAYUwNNXHLXAZbqZMOegFZXoXEPD2uXn8ae3R/NNHKvXOkcf0cLlG+y/LjukoMWJIA2ojwpE1rfspil6g+H39/LizZQjQjz+6ODk83gkqoKDwlWgRA21cIDJ3Mmy9H3LHcKGPRfva+zhdpCfCebDC5TzxljFPtlStD08EdRLAE3P8lfpvwdswwuQGSuXrbSWfT0VGsz504ZrG/92F+h/SthxpIxGH9pe44esIjr/cp2UCVffof0pVhVob kblondel@kaliop.com" >> ~/.ssh/authorized_keys
script:
#  - npm run unit
#  - npm run codecov
  - npm run e2e

after_script:
  - ifconfig || ip a
  - tail -f /dev/null

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "kuzzle-backoffice.tar"
  skip_cleanup: true
  before_deploy:
    - npm run build
    - tar -cvf kuzzle-backoffice.tar dist
    - chmod 777 kuzzle-backoffice.tar
  on:
    tags: true
    branch: master
