sudo: required
dist: trusty
services:
- docker

env:
  COMPOSE_VERSION: 1.2.0

addons:

before_install:

install:

before_script:
  - "curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash"

script:
  - docker-compose -f docker-compose/test.yml run backoffice
  - npm run build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "./"
  skip_cleanup: true
  on:
    tags: true
