sudo: true
services:
- docker
language: node_js
node_js:
- 6.9.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
env:
  DOCKER_COMPOSE_VERSION: 1.9.0
  global:
    - GH_TOKEN:
        secure: Jde8taTSR66BLYjvbwmDRUkLKHvef5m1F5jEfJBOiFSGfWr8ltpjbIMpbU0iAYiDXeAvsvaU/2dpc+qdr4ZBMCPKZ5iXP58kpJvHter0j6zs3+O0Aj/gDZ9/bhi1hAtEjQ0y+MS9QNem9TC7gWSDCtnhi0He+g48ozHakkMVmsmjY676tjkbZ84LLuY4+h3cNK+7gAZqr8Zq0jizTLaJxqoGK1likUWreaVNuXvIlOydiiS6TwYC39N+WiDrxYtEK0RQ8b9g9ITJzTMt8VFd8F0Dziv8Fg+DRcUQTF7N4HPensxhtQeXdX3xuYV0soqMbm8DTq9PaEqX93Wng3tPytGPbFVI76o1rmE4kbFjeWDE6RHcgx9oQSvvEdUGnAy1ww2jdFjbmJ4cxe7S5AEnE1ch52+cCU6Ks1aw/AflgWKRDZQIjppszWHAqTOLbbYREpI7wkYUUowoUrkawvWu0fLMASfpg0tI5QKaIc4dN0bIYOMWxy75CHgL198K8U/sG3lYSKCPU9+Klhy4pNbKJmUDFfnE2FvzVd27dSPLu8uKYXFJuDrq54ykumJRl+hH5S6u0z1nrmZrfXRJGqMJ5UbKhalkHx4opsj4Cr0xwFTR8PbDiSwjLFafHmqSXJ2wh69u1UOlKb/DqanzHTfHMkqNxVdbIOcG4GGtwPX8FGw=
    - TESTIM_TOKEN:
        secure: HjJkPHoB0zqOhYRzLwRevGtezbos2Na9vGo06O/cKIzeL8eFEL12YK5oOD69wvCv3WIEKmrvpSPMNQ4Tw77DZHYCap3mKecZveYAPpW5fKhGGmGUNfX2FV9P84Vf//mN9S6eBwKaUbmvo802EWEjqdSkt1Lvjxb7fxBUxsw55AnVit/0SqDMsJQUUxIobccdfdi3tK4PewXbLpLQbBOtGaZWtBPJExClEA/Y0hHskVzR3yYyC4gObcQk3qkFHo76/qYEzSbz54wJ82X/8QBquNb2tFH6OuCLKL0lKL59+aajZo5UatlL2R9yp1JYhGm6l7tPysFzsPfkpR9BeMT2K3/n9V4cbSZfhDzR8uxfqt2s/ADc1TR8S4CZ+cvczRV3MhbGq4cnfE4d4UQpT4wv5NBFp1KsaW3k0Q1yzNCaTpBJgcsM3QpZrCRL+BP4RGkyjP+iIAqrfAGF6EBe7IKN9fJxf19jk3fRBhKmcWQI+Qpq74XVjlLUWvNe1NgFNMsspaR8JMkRRfwfa3S5VxegmqM9U5yoh3UOyoPWSIdf5HmOlOxwnQyDP3ogRsVfVfo9Jg9Q3sBEzD8NKO5BhBqc+TfzE4H6a3MPlu+VQs08fjxPCHxIm0QIJ6ARogWU/4SH0XSykWvyiojW/vX+pMpdEX3qUMi+/t8TaavXWKCq0h0=
    - TESTIM_PROJECT:
        secure: QqxwuwJWM6EqD3GKHJoVt7c1+EKSh39pVa3QmN32eBTdHIRXEqIrIqW/Aj/94jpyzllwvaIqqCe/mjpIRTA3DKRpVfcF6BDaMf/Gj28CjJ56+2BfgbHHXqAQE88TXTPy+Bw2ILbTwsyxjHW3aRzTRgzWms1qs733KlSYkWxxIARMdXNk7U3APa7kpqeX86m4ZoHEcU9+5TG4ONgtTQVq6DYwfeT/RLLHFmSN458uDaccZOppefq5NbMhu/N8jlA83YJZSOVvXYFXCxho/x4C3iaoO6ZjhiVZJZhECA+8hEP04SanYWc3/Ju0cpCXvq7L05qcOKLdzwbni/m7oeZM0X3cgS1pPw26u03NHPyYE9GSIomBfy7LboDVqCqFNLhn+XRN09lL8RZaoK7zUdFHRdbdZOvPM7oEqzWOvNckZwQFYaSVrUzzRltpc+eFfuiYJ4XfDL97v3jQpzPhIWjmcM+FXY22fl9d2QGLlrvMb+2Rp5M1xTn1LKuFwnunre5OpFk3iJ3kMMGHFb7QuA0cfJ01BBXJcsIDNjPKIQguqMP6hwE1juGuE0pFNnxwdmBrRT2NTMFPuOfToY1OvvTIWQklhShOiPJEH2bhJS5giYRN+J4KGdeJB/z+Lnnq4JWOjhMclj4nr94R+uSO0GiSEPl8wGE9t1EBt3VKNlHx9+I=

before_install:
- npm install -g npm@latest
- export CC="gcc-4.9" CXX="g++-4.9"
script:
- npm run install_deps
- npm run build
- npm run e2e-chrome
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: kuzzle-backoffice.tar
  skip_cleanup: true
  before_deploy:
  - npm run build
  - tar -cvf kuzzle-backoffice.tar dist
  - chmod 777 kuzzle-backoffice.tar
  on:
    tags: true
    branch: master
