sudo: true
services:
- docker
language: node_js
node_js:
- 6.9.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.9.0
  #GH_TOKEN
  - secure: gfJ1/G69s0pOJhqoOB3bMAClvPPj3i++ckCCP/Yz2OMBFoAF3YCb2k2p5fRNX46s/hqkddHZnuSzaPRXHW5tToS7OhpN1HB6EDIfBS80zD1ZH5n5B8s/jKwzQLWv85bZATKc+R8Ir2ukBd/BQFurzd8JtQDpGS2hSCppOUQQApE3F+ghpET8dFPP7qncn1p98UBbbYyxiR53EM2xo93kByooe7nJiwjLvGVCp7zF9ZGKdp+yUzIb5tvOLnxvXrD2IvGl2Cuyf6bdqXUeM5yEhv0JwuD7SsIydCJZhTY8zCkMl3ITThY8HKV19sU6/zlG6aUsD5QAT58DiKk69icRc03kYCeLjUtuVHq/Nzq1grixc/uIi/KJlKxXd6h1NovAhLAkuuqjpLTKePOVeQdwCBZWQdXWPXUBK80px/ZYauydUqmaxHZq5JAM8hg0DbYICCqVcvro7WcUjCEW+VczO36wNU/qjbSsPehysIlWjt7qvcBfGPoGhlIm098jbXNQh0tM3PYInXiIPl/v1ctGUVWBlUkyppxgV3MYHFM04Pwv9lqovWmWuk+c4a22UE08/sTsHHrmS9T4zPfD6d/5Y1v8l8jMc9HGVa2ro642sRGgWS0QkazuQZ4ySYYpt98uv1NMq33L3ffbvsZo2mVCZ1ZWocCG7SbdWhJeOCysMMU=
  #TESTIM_TOKEN
  - secure: G9OGxPEqj7rc4ySl/2L7mbqEKxEchcXu+j/OQsuCWzM/B0bYTjV1ahFKED+WzlsP1f43qhsJ1ImBQPIQTc3nm5K4rUTEzxt7khkWuzAJ5+ahXUxFsFIwJRtAz5GTyJXTkmyMA5iBGt/clAO5X57tUP9EaS6wPbCP8gWrDboDvJIOA/p/0K57n3QTBJCu4kc45mMLFTGAHxkjXL8q5iKel6owbk+DkNt56kU+oVLseEsVCAo5mDoVOVQzgGoBfDU1P2GfLO/dQ9a8+ZRyzOQgduiI+6Rb54Nyg37CZQceuzKDdjJT3fRDXcYJET0wT/0rrktNmvnTwjiAZz0ovyzfDJw+cZqdrbH45tmfFA1BE5vpa9J873H1/egAEAcrM+U+26f19o+k7HUYk0cfqf8G4SClr1lyWu0G2jAEgF33pnuF2YXGM7wvzJzS+Fi9SFklb2PJg/XeI1HTvcLaGxnnpxSMVLbTzUkPL2jdyESLNR/0c2e0iqgqXKXjTZOwCyxCGAMvmsQoH/qZ6+vS1u+Wk8AqrQKEKJvt9hYz5Qo4sHQ6CN+D5rz4EAGd2UexIVZySJZGR88Vmsa2o+qOzXvK+t4YTldx/9vQ4I+m0fvb10455naFCXf1+pIi3QuPityrTZR2Rl6GY/kMM8Ggnce67zQiU9czUqqkXcRXRFudVVU=
  #TESTIM_PROJECT
  - secure: VeDbd/u+/ZbkDWZ75v4EqK41gmve59x+/Hk434XqD0H5Z5ictiPVlYQYk99AxsNYxRaK2JaZwWaJf8DirdD2hjjdAAHArJ31NbyRUQ2YJOnPsxE1IQVk8fXNAdRurwnnO8eV0qylY6ytiGyvbZ45DEb+nmM7CsQg1WxuAVQ5Gw6O72hkqKnTyE3da2Xxcz8yZENsyZR9hit1kuM650yQ6xZ1naHNAdoFOpAKRL2sjD1TwLSGXSrfvn+FMo/jXSO9tFr0LHWMi49U83c9fd2dm8zdTAsPTYrVr33BewGG+uSSKR6MoANG2XHplXJzdSMRsCk7gKt3HcE00eAtMMQgM8xohhiYvz0jzqeRG/5gIT4G2dRRWCb2SunnlPSJU7jSrQAAtakJGsh5OZB1/kiJFZqZqNtD0xJIni4VkMzPpxVuZ+BNPBiDdsE7Atbsr/J4IatYAvnZqNbSLQSK67JXow7cPhLc82ZJX5vYDvHhXhqhTyDqv8xdnSb4V04QGcLw240b0gWWt60E6Ku5jf8j5nHxS4CerX6Ny78A6V7RH42XYqZ3KlH/aHqdA+WsHdUo3k0vG++5DxTh8GZOzESjHdhyJpPDUPjpjkqwAdaf9x9c4tjBroR2nqxNvn9J781VTg0SeM6cM2Wx2PSU3tDk3buZYT10Mp9T8wXxsNj01o8=
before_install:
- npm install -g npm@latest
- export CC="gcc-4.9" CXX="g++-4.9"
script:
- npm run install_deps
- npm run build
- npm run e2e-chrome
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: kuzzle-backoffice.tar
  skip_cleanup: true
  before_deploy:
  - npm run build
  - tar -cvf kuzzle-backoffice.tar dist
  - chmod 777 kuzzle-backoffice.tar
  on:
    tags: true
    branch: master
