sudo: true
services:
- docker
language: node_js
node_js:
- 4.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
env:
  DOCKER_COMPOSE_VERSION: 1.9.0
  global:
  - secure: IVNUEIDEb4Uh/5T+SXIrPuQV8x33Kzhf9oE4hIdsSQFKDNqophryVpSo3Xg34SX1ZViVau9TU8ec2E3zTxPSDyeW5Emfo7Xhzf/6oUQaN3OW+xi1HSCUGg7Tq5jIdRDnVXgFnWLl2fRoGtOrz5lfvQ5e3q6+EpCPyVDUpEjlVNDTibWvibKj4d5BR349THpOeGOUbzr87uke1TOxBkbsceVt55G3xyYRNI6DfLg4MjqaYLzhf5WnduwZc5RyZLFC5EHEhvxRy0BOfbpF20NBva05qjO1GcuNaHPfJhuuQcsaSAGmzHXi67QvDAjmCLLd7lA5HwCC2+51CGccw/CqnM64cZIJVMZnh68wd9gRHszKU8VhMx8K2eNPcGa5WTER+ald5pK2XBycm/fUNPTy/3zf30Svk5l9pyuT22WepGHmWrPxU3HzxpyGE0zPcPmzVjl23J40PBIHAHt3p2yoX2fQOKsA7c7dci6lcgX/aO3g6UGY8nd8OtEmeP9FybgVgNqJGdQP6gtT7rk6zf0lStbkC0RWu52GvLxTLthDgaQkqOFjwc0tVDYydsNZ/n046uDXw1eytt8lJT7ayu0+mnT2jzsLBvCDia1uwVRr5zHZUAuYHk+P5FM7yMjv5BaMwMbnSxU1AgIe+n0ojeb/f5wuKMBbGXTReyszPrXq/AY=
  - secure: nT/NnVnX3IxxodJtgcglg40U2tgkvkMY3s1x06sIR45Y1ze6J3wmlhcfwxNcjMc/QGZrymEJ6WBoS0gkqCnBPVFAFlDw9+wgEWUsLidI2uybIdz3Fgpj3YM10t3wSLiyYV/LcVb/ef3bF2VRIKfg+ak4gVRMrj3+GyKf3bON+ZptQY6jqLj/PZnsFhuOkYpunaKofbmTOseZoYmQPRzAqGs+wbkXe7gBdlRtjbb2AUKekN0S2y6EiPjHRBT6he1U4sNwYD/UTnrWORbN2tDfncLdGq2meSI/jnSVD8HWxGgc+dSMibsvdZ48tkVlzBdw46Einb+ZRTPdwBas6M29Qqqq8VbFlGLb0cy9+nikyquCXEIgZ2BZIaROs92LJAtmpKRzlLUw4VO6PyYQrG9SpAZMOr6JxGb6PQdOojD/Kt5iHMA+RCrrTNESLbLpZJqfgwfMjYrpNywINYbCmlrXku5j34lHsMC2F2utyUrPxOZHyphmkToHwVms+FyDOhjLvYHyr/p0T5dJ85uOHZFfobgmB+AIZhCCocYXQCZFxEdgte1CJCZBTcKf5Tp91m99+MNqa5AjGqYhv/SrLCmWvBYAlX4n4eHrAcv3gyF0VDKbitMv4q80iJAj47BnOOewBr1EMBir5FA+jwjQEDGhx/6/XttWvPTZfeGkDStcIW8=
  - secure: M8v4VNNB/LYhWdUibvNAipiQh0fORMiCKH4QxgqnsStl7IR61NvkuLjORu92q3CNxbLp3jUxQDbtkRVwQ5jUhyV17O/zGkfkRSTesAAjF+Zacef1sq8HW2Ep2Ir7gI34MXmKcgQsxSRN2zO5QxgcYE9jkuhpbDKHkW481BAaT8OOx4ImcfKBtedDPC/KEC9etcEgqRi9d2APJXS4OJwRVaLntYb2mn/BXV3q/lHjwKWDLxG3R44dI7CHl9gvdjHzv+mY8VIDFVtRGJNshniirUWdlgSgwGG2A5KjMVVDXDdI3wrSzaU86mkBkC54D3ujskZUXcAQtneF/4xCYqFkKTBX5T79y27T1RXVsCKCPCG1aZWRHS5pEdPCMzpXY5nOdGXM6GyciOFIHWe8rf8j/JfVD83UUytpHn3Ge5c9KaXBpB08GHmBgGqR5VwefRKxfE0M/teT17EX1zQE4OF6VouIU4o/V3zpNWp/jV4eZ8kUUlKiLYvV5QYcQ6V6ixyxyRFAOL9t3HoSiIaNQwtM6Fg01yI4KL/1t5GKHDyMJEb0yNSZb3POgyvw7YDCOeXEBG9Pxom7/WnWXdT5ILfOhFTzVFUWydKtqbGCYxKo3uG7GcwglsAjTxld/NtfdN31tNPUrbtcYfKhY0SFxABeFmOlZNDY8UItLjqz4FYDPhA=

before_install:
- npm install -g npm@latest
- export CC="gcc-4.9" CXX="g++-4.9"

script:
- npm run install_deps
- npm run build
- npm run e2e-chrome
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: kuzzle-backoffice.tar
  skip_cleanup: true
  before_deploy:
  - npm run build
  - tar -cvf kuzzle-backoffice.tar dist
  - chmod 777 kuzzle-backoffice.tar
  on:
    tags: true
    branch: master
