proxy:
  image: kuzzleio/proxy
  ports:
    - "7511-7513:7511-7513"

backoffice:
  image: kuzzleio/backoffice
  environment:
    - BACKEND_HOST
    - BACKEND_PORT
  ports:
    - 3000:3000
  environment:
    - BACKOFFICE_PORT

kuzzle:
  image: kuzzleio/kuzzle
  links:
    - elasticsearch
    - redis
    - proxy
  environment:
    - kuzzle_services__db__host=elasticsearch
    - kuzzle_services__internalCache__node__host=redis
    - kuzzle_services__memoryStorage__node__host=redis
    - kuzzle_services__proxyBroker__host=proxy

redis:
  image: redis:3.2-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.3.4
