version: '2'

services:
  backoffice:
    image: kuzzleio/dev
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-dev.sh:/run.sh"
    ports:
      - "3000:3000"
    environment:
      - DEBUG_PHANTOM
