version: '2'

services:
  proxy:
    image: kuzzleio/proxy
    ports:
      - "7512:7512"

  backoffice:
    image: kuzzleio/dev
    command: sh -c 'chmod 755 /run.sh && /run.sh'
    volumes:
      - "..:/var/app"
      - "./scripts/run-dev.sh:/run.sh"
    ports:
      - "3000:3000"
    environment:
      - DEBUG_PHANTOM

  kuzzle:
    image: kuzzleio/kuzzle:develop
    volumes:
        - "../../kuzzle/:/var/app"
        - "../kuzzle/fixtures.json:/fixtures.json"
        - "../kuzzle/mappings.json:/mappings.json"
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - kuzzle_fixtures=/fixtures.json
      - kuzzle_mappings=/mappings.json

  redis:
    image: redis:3.2-alpine

  elasticsearch:
    image: elasticsearch:5.0
